export const categorys = [
    { name: "Fantasy hbdhbhxcbchbxhcbxhchxcbhxcxhcxc", image: "fantasy.jpg" },
    { name: "Mystery", image: "mystery.jpg" },
    { name: "Thriller", image: "thriller.jpg" },
    { name: "Adventure", image: "adventure.jpg" },
    { name: "Biography", image: "biography.jpg" },
    { name: "Self-help", image: "self_help.jpg" },
    { name: "Poetry", image: "poetry.jpg" },
    { name: "Dystopian", image: "dystopian.jpg" },
    { name: "Young Adult", image: "young_adult.jpg" },
    { name: "Children's", image: "childrens.jpg" },
    { name: "Cooking", image: "cooking.jpg" },
    { name: "Travel", image: "travel.jpg" },
    { name: "Art", image: "art.jpg" },
    { name: "Science", image: "science.jpg" },
    { name: "Technology", image: "technology.jpg" },
    { name: "Business", image: "business.jpg" },
    { name: "Finance", image: "finance.jpg" },
    { name: "Health", image: "health.jpg" },
    { name: "Fitness", image: "fitness.jpg" },
    { name: "Music", image: "music.jpg" },
    { name: "Education", image: "education.jpg" },
    { name: "Religion", image: "religion.jpg" },
    { name: "Philosophy", image: "philosophy.jpg" },
    { name: "Sports", image: "sports.jpg" },
    { name: "Psychology", image: "psychology.jpg" },

  ];