export const books = [
    { title: "Fantasy hbdhbhxcbchbxhcbxhchxcbhxcxhcxc", image: "fantasy.jpg" },
    { title: "Mystery", image: "mystery.jpg" },
    { title: "Thriller", image: "thriller.jpg" },
    { title: "Adventure", image: "adventure.jpg" },
    { title: "Biography", image: "biography.jpg" },
    { title: "Self-help", image: "self_help.jpg" },
    { title: "Poetry", image: "poetry.jpg" },
    { title: "Dystopian", image: "dystopian.jpg" },
    { title: "Young Adult", image: "young_adult.jpg" },
    { title: "Children's", image: "childrens.jpg" },
    { title: "Cooking", image: "cooking.jpg" },
    { title: "Travel", image: "travel.jpg" },
    { title: "Art", image: "art.jpg" },
    { title: "Science", image: "science.jpg" },
    { title: "Technology", image: "technology.jpg" },
    { title: "Business", image: "business.jpg" },
    { title: "Finance", image: "finance.jpg" },
    { title: "Health", image: "health.jpg" },
    { title: "Fitness", image: "fitness.jpg" },
    { title: "Music", image: "music.jpg" },
    { title: "Education", image: "education.jpg" },
    { title: "Religion", image: "religion.jpg" },
    { title: "Philosophy", image: "philosophy.jpg" },
    { title: "Sports", image: "sports.jpg" },
    { title: "Psychology", image: "psychology.jpg" },

  ];